version: '3'

services:
  consulserver01:
    image: consul:1.10
    container_name: consulserver01
    hostname: consulserver01
    command: >
      consul agent -server -bootstrap-expect=3 -node=consulserver01
      -bind=0.0.0.0 -data-dir=/consul/data -config-dir=/etc/consul.d
      -retry-join=consulserver02 -retry-join=consulserver03
      -encrypt=${CONSUL_ENCRYPT_KEY}
    volumes:
      - ./servers/server01:/etc/consul.d
    ports:
      - "8500:8500"

  consulserver02:
    image: consul:1.10
    container_name: consulserver02
    hostname: consulserver02
    command: >
      consul agent -server -node=consulserver02
      -bind=0.0.0.0 -data-dir=/consul/data -config-dir=/etc/consul.d
      -retry-join=consulserver01 -retry-join=consulserver03
      -encrypt=${CONSUL_ENCRYPT_KEY}
    volumes:
      - ./servers/server02:/etc/consul.d

  consulserver03:
    image: consul:1.10
    container_name: consulserver03
    hostname: consulserver03
    command: >
      consul agent -server -node=consulserver03
      -bind=0.0.0.0 -data-dir=/consul/data -config-dir=/etc/consul.d
      -retry-join=consulserver01 -retry-join=consulserver02
      -encrypt=${CONSUL_ENCRYPT_KEY}
    volumes:
      - ./servers/server03:/etc/consul.d

  consulclient01:
    image: consul:1.10
    container_name: consulclient01
    hostname: consulclient01
    command: >
      consul agent -node=consulclient01
      -data-dir=/consul/data -config-dir=/etc/consul.d
      -retry-join=consulserver01 -retry-join=consulserver02 -retry-join=consulserver03
      -encrypt=${CONSUL_ENCRYPT_KEY}
    volumes:
      - ./clients/consul01:/etc/consul.d

  consulclient02:
    image: consul:1.10
    container_name: consulclient02
    hostname: consulclient02
    command: >
      consul agent -node=consulclient02
      -data-dir=/consul/data -config-dir=/etc/consul.d
      -retry-join=consulserver01 -retry-join=consulserver02 -retry-join=consulserver03
      -encrypt=${CONSUL_ENCRYPT_KEY}
    volumes:
      - ./clients/consul02:/etc/consul.d
